AWSTemplateFormatVersion: '2010-09-09'
Description: Basic EC2 setup for student app

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and App Port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
#      RoleName: EC2-CodeDeploy-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
##    ImageId: ami-0f58b397bc5c1f2e8
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      KeyName: student-key
      SecurityGroupIds:
        - !Ref MySecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: App
          Value: student-app
        - Key: Name
          Value: student-app-server
    
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e   # stops script if any command fails
          yum update -y
          yum install -y ruby wget

          cd /home/ec2-user
          wget https://aws-codedeploy-ap-south-1.s3.ap-south-1.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto

          systemctl start codedeploy-agent
          systemctl enable codedeploy-agent
  
  MyCodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: student-app
    CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  MyDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref MyCodeDeployApp
      DeploymentGroupName: student-app-dg
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      DeploymentStyle:
        DeploymentType: IN_PLACE
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
      Ec2TagFilters:
        - Key: App
          Value: student-app
          Type: KEY_AND_VALUE 
  ArtifactBucket:
  Type: AWS::S3::Bucket

  CodeBuildRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
  MyCodeBuild:
  Type: AWS::CodeBuild::Project
  Properties:
    Name: student-app-build
    Source:
      Type: CODEPIPELINE
    Artifacts:
      Type: CODEPIPELINE
    Environment:
      ComputeType: BUILD_GENERAL1_SMALL
      Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
      Type: LINUX_CONTAINER
      PrivilegedMode: false
    ServiceRole: !GetAtt CodeBuildRole.Arn    
CodePipelineRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
MyPipeline:
  Type: AWS::CodePipeline::Pipeline
  Properties:
    RoleArn: !GetAtt CodePipelineRole.Arn
    ArtifactStore:
      Type: S3
      Location: !Ref ArtifactBucket
    Stages:
      - Name: Source
        Actions:
          - Name: SourceAction
            ActionTypeId:
              Category: Source
              Owner: AWS
              Provider: CodeStarSourceConnection
              Version: 1
            OutputArtifacts:
              - Name: SourceOutput
            Configuration:
              ConnectionArn: arn:aws:codeconnections:ap-south-1:628203514915:connection/ef57f8eb-cf0e-4c71-926e-e1f4e038bc7e
              FullRepositoryId: tanmayakrout/student-app
              BranchName: main
      - Name: Build
        Actions:
          - Name: BuildAction
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: 1
            InputArtifacts:
              - Name: SourceOutput
            OutputArtifacts:
              - Name: BuildOutput
            Configuration:
              ProjectName: !Ref MyCodeBuild
      - Name: Deploy
        Actions:
          - Name: DeployAction
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CodeDeploy
              Version: 1
            InputArtifacts:
              - Name: BuildOutput
            Configuration:
              ApplicationName: !Ref MyCodeDeployApp
              DeploymentGroupName: !Ref MyDeploymentGroup    